name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up MSBuild
        uses: microsoft/setup-msbuild@v1

      - name: Restore NuGet packages
        run: nuget restore WebApp_Git.sln

      - name: Build App
        run: msbuild WebApp_Git.sln /p:Configuration=Release

      - name: Publish Build Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: BuildArtifacts
          path: |
            **/bin/Release/
            **/obj/Release/

  deploy-local:
    runs-on: self-hosted
    needs: build
    if: github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Deployment Directory
        run: mkdir -p C:\Users\SMALLAPR\source\repos\deploy

      - name: Copy Build Artifacts
        run: |
          echo "Deploying to local folder"
          cp -r C:\Users\SMALLAPR\actions-runner\_work\Git-Demo-App\Git-Demo-App\bin\Release\* C:\Users\SMALLAPR\source\repos\deploy\
